<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="LAPTOP-UNO4ULJI" failures="3" tests="4" name="Default test(failed)" time="9.722" errors="0" timestamp="2022-10-21T13:57:44 IST">
  <testcase classname="TestCases.failedTest" name="loginToApp2Test" time="0.01">
    <failure type="java.lang.AssertionError" message="expected [null] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [null] but found [false]
at TestCases.failedTest.loginToApp2Test(failedTest.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- loginToApp2Test -->
  <testcase classname="TestCases.failedTest" name="verifyloginLogoTest" time="0.048">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at TestCases.failedTest.verifyloginLogoTest(failedTest.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verifyloginLogoTest -->
  <testcase classname="TestCases.failedTest" name="verifyTitleTest" time="0.008"/>
  <testcase classname="TestCases.failedTest" name="verifybotLogoTest" time="0.033">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at TestCases.failedTest.verifybotLogoTest(failedTest.java:46)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verifybotLogoTest -->
  <testcase classname="TestCases.failedTest" name="loginToAppTest" time="0.0">
    <ignored/>
  </testcase> <!-- loginToAppTest -->
  <testcase classname="TestCases.failedTest" name="verifyurlTest" time="0.0">
    <ignored/>
  </testcase> <!-- verifyurlTest -->
</testsuite> <!-- Default test(failed) -->
